language: java
jdk:
  - oraclejdk8

before_script:
  - echo $PWD
  - export SQLITEVERSION=3150000
  - curl -O http://sqlite.org/2016/sqlite-autoconf-$SQLITEVERSION.tar.gz
  - tar xzvf sqlite-autoconf-$SQLITEVERSION.tar.gz
  - cd sqlite-autoconf-$SQLITEVERSION
  - export CFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1"
  - ./configure --disable-dependency-tracking --prefix=$PWD
  - make install
  - cd -

script:
  - echo $SQLITEVERSION
  - mvn -Djna.library.path=$PWD/sqlite-autoconf-$SQLITEVERSION/lib test