install:
 - cinst sqlite
 - cinst maven
 - cmd: ECHO %PATH%
 - cmd: SET PATH=C:\bin\apache-maven-3.3.1\bin;%PATH%
 - cmd: SET MAVEN_OPTS=-Djna.library.path=C:\tools\SQLite
build_script:
 - mvn clean package --batch-mode -DskipTest
test_script:
 - mvn clean install --batch-mode
cache:
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml
 - C:\Users\appveyor\.m2
