branches:
 only:
  - master
skip_tags: true
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
 - cinst sqlite # win32_x86 dll
 - cinst maven
 - cmd: SET
 - cmd: SET PATH=C:\bin\apache-maven-3.3.1\bin;%PATH%
 - cmd: SET MAVEN_OPTS=-Djna.library.path=C:\tools\SQLite
build_script:
 - mvn -V clean package --batch-mode -DskipTests
test_script:
 - mvn clean install --batch-mode
cache:
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml
 - C:\Users\appveyor\.m2
