branches:
  only:
    - master
skip_tags: true
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  M2_HOME: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.4
install:
  - ps: |
      $MVNDIR = $env:M2_HOME
      if (!(Test-Path -Path $MVNDIR )) {
        Write-Host (Test-Path -Path $MVNDIR)
        Write-Host 'Installing Maven'
        choco install maven --version 3.5.4 -y
      } else {
        Write-Host 'Found Maven cached installation'
      }
  - cmd: SET PATH=%M2_HOME%\bin;%PATH%
#  - cinst sqlite # win32_x86 dll versus JDK amd64
  - ps: Start-FileDownload 'http://sqlite.org/2018/sqlite-dll-win64-x64-3250200.zip'
  - cmd: 7z e sqlite-dll-win64-x64-3250200.zip -y > nul
build_script:
  - mvn -V -B clean package -DskipTests
test_script:
  - mvn -B test -DargLine="-Djna.library.path=C:/projects/sqlite-jna/ -Djna.nosys=true -Djna.debug_load=true"
cache:
  - C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.4
  - C:\Users\appveyor\.m2
