branches:
  only:
    - master
skip_tags: true
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  M2_HOME: C:\bin\apache-maven-3.2.5
install:
# https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki
#  - cinst sqlite # win32_x86 dll versus JDK amd64
  - ps: |
      $MVNDIR = $env:M2_HOME
      if (!(Test-Path -Path $MVNDIR )) {
        Write-Host (Test-Path -Path $MVNDIR)
        Write-Host 'Installing Maven'
        choco install maven -Version 3.2.5
      } else {
        Write-Host 'Found Maven cached installation'
      }
  - cmd: SET PATH=%M2_HOME%\bin;%PATH%
before_build:
# PM> Install-Package System.Data.SQLite.Core
  - nuget restore
build_script:
  - mvn -V -B clean package -DskipTests
test_script:
  - mvn -B test -DargLine="-Djna.library.path=C:\tools\SQLite -Djna.nosys=true"
cache:
  - C:\bin\apache-maven-3.2.5\
  - C:\Users\appveyor\.m2
