branches:
  only:
    - master
skip_tags: true
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  M2_HOME: C:\tools\apache-maven-3.3.3
install:
  - ps: |
      $MVNDIR = $env:M2_HOME
      if (!(Test-Path -Path $MVNDIR )) {
        Write-Host (Test-Path -Path $MVNDIR)
        Write-Host 'Installing Maven'
        choco install maven -Version 3.3.3 -y
      } else {
        Write-Host 'Found Maven cached installation'
      }
  - cmd: SET PATH=%M2_HOME%\bin;%PATH%
#  - cinst sqlite # win32_x86 dll versus JDK amd64
  - ps: Start-FileDownload 'http://sqlite.org/2016/sqlite-uap-3100200.vsix'
#  - cmd: 7z e sqlite-uap-3100200.vsix Redist\Retail\x64\sqlite3.dll -y -osrc\main\resources\win32-x86-64\
  - cmd: 7z x sqlite-uap-3100200.vsix Redist\Retail\x64\ -y
  - cmd: dir Redist\Retail\x64\
build_script:
  - mvn -V -B clean package -DskipTests
test_script:
  - mvn -B test -DargLine="-Djna.library.path=C:/projects/sqlite-jna/Redist/Retail/x64/ -Djna.nosys=true -Djna.debug_load=true"
cache:
  - C:\tools\apache-maven-3.3.3
  - C:\Users\appveyor\.m2
